version: '3.7'

services:
  database:
    image: postgres
    container_name: database_todo
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todotest
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: todotest
    ports:
      - 3333:3333
    environment:
      PORT: 3333
      DATABASE_URL: postgres://postgres:admin@db:5432/todotest
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
